### ISSUE TITLE
Make auth screen

### ISSUE THREAD

**Issue by RafaelGoulartB** [RafaelGoulartB/coinbase-mobile#3]
# Tasks
- [ ] add authentication flow with context api
- [ ] add login/resister page
- [ ] add reset password page
